name: Build and Publish Dist

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build dist using Docker + Makefile
        run: make build-dist

      - name: Checkout dist repo
        uses: actions/checkout@v4
        with:
          repository: ministryofjustice/opg-hugerte-angular-dist
          token: ${{ secrets.GH_TOKEN }}
          path: dist-repo

      - name: Copy built dist into dist repo
        run: |
          rm -rf dist-repo/*
          cp -r dist/* dist-repo/

      - name: Commit and push changes
        run: |
          cd dist-repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update dist from opg-hugerte-angular @ $GITHUB_SHA" || echo "No changes to commit"
          git push origin main

      - name: Tag release in dist repo (only on tag push)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cd dist-repo
          TAG=${GITHUB_REF#refs/tags/}
          git tag $TAG
          git push origin $TAG
