name: Build Dist (PR check)

on:
  pull_request:
    branches:
      - main

jobs:
  build-only:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: make build-dist

      - name: Upload dist as artifact (Just to test for now)
        uses: actions/upload-artifact@v4
        with:
          name: dist-build
          path: dist/
